language: cpp

# For Ubuntu 14.04 C++11/15 support ...
sudo: required
dist: trusty

compiler:  
    - gcc

before_script:
    - git submodule update --init --recursive
    - sudo apt-get install build-essential
    - sudo apt-get install cmake
    - mkdir build
    - cd build
    - cmake .. -DBUILD_GMOCK=On
    - make

script: ./tests/order 
